spring:
  datasource:
    url: jdbc:mysql://${zlt.datasource.ip}:3306/product-manager?useUnicode=true&characterEncoding=UTF-8&autoReconnect=true&useSSL=false&zeroDateTimeBehavior=convertToNull&serverTimezone=Asia/Shanghai
    username: ${zlt.datasource.username}
    password: ${zlt.datasource.password}
    driver-class-name: com.mysql.cj.jdbc.Driver

mybatis-plus:
  mapper-locations: classpath:/mapper/*Mapper.xml
  #实体扫描，多个package用逗号或者分号分隔
  typeAliasesPackage: com.central.base.model
  global-config:
    db-config:
      id-type: auto

zlt:
  swagger:
    enabled: true
    title: 基础模块中心
    description: 基础模块接口文档
    version: 1.0
    base-package: com.central.base.controller
  cache-manager:
    configs:
      - key: base
        second: 300
      - key: base
        second: 1800
  #多租户配置
  tenant:
    enable: false
    ignoreTables:
      - sys_user
      - sys_role_user
      - sys_role_menu
    ignoreSqls:
      # 用户关联角色时，显示所有角色
      - com.central.user.mapper.SysRoleMapper.findAll
      # 用户列表显示用户所关联的所有角色
      - com.central.user.mapper.SysUserRoleMapper.findRolesByUserIds
  #审计日志
#  audit-log:
#    enabled: true
#    log-type: db
#    datasource:
#      driver-class-name: com.mysql.cj.jdbc.Driver
#      jdbc-url: jdbc:mysql://${zlt.datasource.ip}:3306/logger-center?useUnicode=true&characterEncoding=UTF-8&autoReconnect=true&useSSL=false&zeroDateTimeBehavior=convertToNull&serverTimezone=Asia/Shanghai
#      username: ${zlt.datasource.username}
#      password: ${zlt.datasource.password}
